name: Test

on:
  push:
    branches-ignore:
      - main
      - alpha
      - beta
      - next

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm ci

      - run: npm run lint

      - run: npm run types

      - run: npm test
